version: "3.8"

services:
  tasks_back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasks_back
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver ${SERVER_HOST}:${SERVER_PORT}"
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - port=${SERVER_PORT}
    depends_on:
      - tasks_db

  tasks_db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    container_name: "${POSTGRES_SERVER}"


